#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ENV_FILE="${HOME}/.dougie/release-keystore.env"
mkdir -p "${HOME}/.dougie"
chmod 700 "${HOME}/.dougie"
umask 077

banner "Dougie upload keystore → GitHub Release"

# ── 1. Tools ──────────────────────────────────────────────────────────────
stage "Check keytool and gh"
say "Release CI needs four repo secrets: ANDROID_KEYSTORE_BASE64,"
say "ANDROID_KEYSTORE_PASSWORD, ANDROID_KEY_ALIAS, ANDROID_KEY_PASSWORD."
say "Play and sideload GitHub APKs share this one upload cert."
note "Passwords stay in ${ENV_FILE} (mode 600), never in git."
if ! command -v keytool >/dev/null 2>&1; then
  warn "keytool not found. Install JDK 17 and re-run."
  exit 1
fi
if ! command -v gh >/dev/null 2>&1; then
  warn "gh not found. Install GitHub CLI and re-run."
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  warn "gh is not logged in. Run: gh auth login"
  open_url "https://github.com/login"
  pause "Press Enter after gh auth login succeeds."
  gh auth status >/dev/null 2>&1 || { warn "still not logged in"; exit 1; }
fi
note "keytool and gh are ready."
pause "Continue?"

# ── 2. Keystore ───────────────────────────────────────────────────────────
stage "Create or reuse the upload keystore"
say "Keep this file forever. Losing it means users must uninstall to update."
DEFAULT_STORE="${HOME}/.dougie/dougie-upload.jks"
if [[ -f "$DEFAULT_STORE" ]]; then
  note "Found existing $DEFAULT_STORE"
fi
if confirm "Generate a new keystore at ${DEFAULT_STORE}?"; then
  if [[ -f "$DEFAULT_STORE" ]]; then
    warn "File already exists. Choose No on generate and import it, or move it aside."
    exit 1
  fi
  ask_secret ANDROID_KEYSTORE_PASSWORD "Keystore password:"
  [[ -n "$ANDROID_KEYSTORE_PASSWORD" ]] || { warn "password required"; exit 1; }
  ask_secret ANDROID_KEY_PASSWORD "Key password (empty = same as keystore):"
  [[ -z "$ANDROID_KEY_PASSWORD" ]] && ANDROID_KEY_PASSWORD="$ANDROID_KEYSTORE_PASSWORD"
  ANDROID_KEY_ALIAS="dougie-upload"
  ANDROID_KEYSTORE_PATH="$DEFAULT_STORE"
  keytool -genkeypair \
    -keystore "$ANDROID_KEYSTORE_PATH" \
    -storetype PKCS12 \
    -alias "$ANDROID_KEY_ALIAS" \
    -keyalg RSA \
    -keysize 3072 \
    -validity 10000 \
    -dname "CN=Dougie, OU=Release, O=IAmKings, C=CN" \
    -storepass "$ANDROID_KEYSTORE_PASSWORD" \
    -keypass "$ANDROID_KEY_PASSWORD" >/dev/null
  chmod 600 "$ANDROID_KEYSTORE_PATH"
  say "Created $ANDROID_KEYSTORE_PATH"
else
  ask ANDROID_KEYSTORE_PATH "Path to existing .jks / .p12:"
  ask ANDROID_KEY_ALIAS "Key alias:"
  ask_secret ANDROID_KEYSTORE_PASSWORD "Keystore password:"
  ask_secret ANDROID_KEY_PASSWORD "Key password (empty = same as keystore):"
  [[ -z "$ANDROID_KEY_PASSWORD" ]] && ANDROID_KEY_PASSWORD="$ANDROID_KEYSTORE_PASSWORD"
  [[ -f "$ANDROID_KEYSTORE_PATH" ]] || { warn "file not found: $ANDROID_KEYSTORE_PATH"; exit 1; }
  keytool -list \
    -keystore "$ANDROID_KEYSTORE_PATH" \
    -storepass "$ANDROID_KEYSTORE_PASSWORD" >/dev/null \
    || { warn "keytool could not open that keystore"; exit 1; }
fi
write_env ANDROID_KEYSTORE_PATH "$ANDROID_KEYSTORE_PATH"
write_env ANDROID_KEY_ALIAS "$ANDROID_KEY_ALIAS"
write_env ANDROID_KEYSTORE_PASSWORD "$ANDROID_KEYSTORE_PASSWORD"
write_env ANDROID_KEY_PASSWORD "$ANDROID_KEY_PASSWORD"
chmod 600 "$ENV_FILE" "$ANDROID_KEYSTORE_PATH"

# ── 3. Backup ─────────────────────────────────────────────────────────────
stage "Backup the keystore"
step "Copy ${ANDROID_KEYSTORE_PATH} and ${ENV_FILE} to a password manager or encrypted disk."
step "Do not commit them. Do not AirDrop unencrypted."
warn "There is no recovery if both copies are lost."
pause "Press Enter after the backup exists."

# ── 4. GitHub secrets ─────────────────────────────────────────────────────
stage "Write GitHub Actions secrets"
say "CI reads these names from .github/workflows/release.yml."
open_url "https://github.com/IAmKings/Dougie/settings/secrets/actions"
if ! confirm "Set ANDROID_KEYSTORE_* on IAmKings/Dougie now?"; then
  SKIPPED+=("GitHub secrets (you skipped set)")
  warn "skipped secret upload"
else
  B64=$(base64 < "$ANDROID_KEYSTORE_PATH" | tr -d '\n')
  set_secret ANDROID_KEYSTORE_BASE64 "$B64"
  unset B64
  set_secret ANDROID_KEYSTORE_PASSWORD "$ANDROID_KEYSTORE_PASSWORD"
  set_secret ANDROID_KEY_ALIAS "$ANDROID_KEY_ALIAS"
  set_secret ANDROID_KEY_PASSWORD "$ANDROID_KEY_PASSWORD"
fi

# ── 5. Re-run Release ─────────────────────────────────────────────────────
stage "Rebuild v0.1.0 with the upload key"
say "This replaces the debug-signed APKs on the existing GitHub Release."
say "Phones that already installed the debug v0.1.0 must uninstall first."
open_url "https://github.com/IAmKings/Dougie/releases/tag/v0.1.0"
if confirm "Dispatch workflow Release with tag=v0.1.0 from master?"; then
  if gh workflow run Release --ref master -f tag=v0.1.0; then
    say "Workflow requested."
    open_url "https://github.com/IAmKings/Dougie/actions/workflows/release.yml"
  else
    SKIPPED+=("gh workflow run Release (run it from the Actions tab)")
    warn "could not dispatch; start Release manually and set tag to v0.1.0"
  fi
else
  SKIPPED+=("Release workflow dispatch")
fi
pause "Press Enter to finish."

finish
note "After the job is green, the Release should no longer be pre-release."
note "Uninstall debug-signed Dougie before installing the new APKs."

